version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: FSO22_Part13 Default is postgres
    container_name: songify-dev-db
    ports:
      - 5432:5432
  api:
    image: songify-api-img
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://root:sekret@songify-dev-db:5432/postgres?schema=public
    ports:
      - 8080:8080
  metricbeat:
    image: docker.elastic.co/beats/metricbeat-oss:8.7.0
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./elastic-search/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
      - KIBANA_HOST=http://localhost:5601
      # - LOGSTASH_HOST=http://logstash:5044
      - ENABLE_CONTAINER_MODULE=true
      - MODULES=container
    depends_on:
      - api
    container_name: songify-dev-metricbeat

# networks:
#   external:
#     elastic: