version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: FSO22_Part13 Default is postgres
    container_name: songify-dev-db
    ports:
      - 5432:5432
  api:
    image: songify-api-img
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://root:sekret@songify-dev-db:5432/postgres?schema=public
    ports:
      - 8080:8080
