# Got some assistance from ChatGPT & https://stackoverflow.com/questions/62037965/about-docker-containers-exit-when-docker-compose-up
# Don't forget to sudo sysctl -w vm.max_map_count=262144
version: '3'
services:
  es-node01:
    container_name: es-node01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    stdin_open: true
    tty: true
  kibana-01:
    container_name: kibana-01
    image: docker.elastic.co/kibana/kibana:8.7.0
    ports:
      - "5601:5601"
    networks:
      - elastic
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

networks:
  elastic:
    driver: bridge
