version: '3.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0-amd64
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    container_name: songify-dev-elasticsearch
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0-amd64
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    container_name: songify-dev-kibana
    ports:
      - 5601:5601
  metricbeat:
    image: docker.elastic.co/beats/metricbeat-oss:8.7.0-amd64
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=elasticsearch:9200
    container_name: songify-dev-metricbeat
