metricbeat.modules:
- module: docker
  metricsets: ["container"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s
  containers:
    ids:
      - "api"

output.elasticsearch:
  hosts: ["https://es-node01:9200"] # Here I tried host from the container
  username: "elastic"
  password: "pass"
  ssl:
    enabled: true
    certificate_authorities: ["http_ca.crt"] # can't because we're inside container & this is for localhost
    
        