metricbeat.modules:
- module: docker
  metricsets: ["container"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s
  containers:
    ids:
      - "api"

output.elasticsearch:
  hosts: ["https://elastic-search_elastic:9200"] # Here I tried host from the container
  username: "elastic"
  password: "pass"
